[Config]
Dependencies=base

[Output]
Format=disk
Output=sys-kde
ImageVersion=20260831
SplitArtifacts=yes

[Content]
BaseTrees=%O/base
UsrOnly=yes
Packages=
    patterns-kde-kde
    patterns-kde-kde_plasma
    sddm
    firefox
    dolphin
    konsole
    kdeplasma6-addons
    kate
