[Config]
Dependencies=base

[Output]
Format=disk
ImageId=proto-kde
ImageVersion=20260831
Output=%i-%v.%a
CompressOutput=xz
ManifestFormat=json
SplitArtifacts=uki

[Validation]
Checksum=yes

[Content]
BaseTrees=%O/base
ExtraTrees=%D/mkosi.extra
SELinuxRelabel=no
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
FinalizeScripts=%D/mkosi.finalize.chroot
PostOutputScripts=%D/mkosi.postoutput
KernelCommandLine=
    root=gpt-auto
    rootfstype=btrfs
    rw
    security=selinux
    selinux=1
    enforcing=0
    system.deployment=proto-kde-20260831.x86-64
    rd.systemd.mount-extra=/dev/gpt-auto-root:/sysroot/.system:btrfs:subvol=/,nodev,nosuid,x-gvfs-hide,x-gdu.hide
    rd.systemd.mount-extra=/sysroot/.system/@deployments/proto-kde-20260831.x86-64.usr.erofs:/sysroot/usr:erofs:ro,loop,x-systemd.requires-mounts-for=/sysroot/.system/@deployments/proto-kde-20260831.x86-64.usr.erofs
    rd.systemd.mount-extra=/dev/gpt-auto-root:/sysroot/etc:btrfs:subvol=/@etc-proto-kde-20260831
Packages=
    patterns-kde-kde_plasma
    ark
    aurorae6
    bluedevil6
    breeze6-wallpapers
    ddcutil-i2c-udev-rules
    desktop-data
    sddm
    discover6
    discover6-backend-flatpak
    discover6-backend-fwupd
    discover6-notifier
    dolphin
    ffmpegthumbs
    flatpak-kcm6
    kaccounts-integration
    kaccounts-providers
    kde-gtk-config6-gtk3
    kde-inotify-survey
    kde-linux-sysupdated
    kde-print-manager
    kdeconnect-kde
    kdegraphics-thumbnailers
    kdenetwork-filesharing
    konsole
    kdnssd
    kf6-baloo-file
    kf6-purpose
    kf6-qqc2-desktop-style
    kgamma6
    kio-extras
    kio-fuse
    kio-gdrive
    ksshaskpass6
    kunifiedpush
    kwalletmanager
    kdeplasma6-addons
    kate
    libappindicator3-1
    Mesa-demo-egl
    ocean-sound-theme6
    pam_kwallet6
    partitionmanager
    pinentry
    plasma-browser-integration
    plasma6-desktop-emojier
    plasma6-nm-openconnect
    plasma6-nm-openvpn
    plasma6-pa
    plasma6-systemmonitor
    plasma6-workspace-wallpapers
    qt6-imageformats
    sddm-kcm6
    spectacle
    zenity
