[Content]
ExtraTrees=%D/mkosi.initrd.extra
SELinuxRelabel=no
RemoveFiles=
    /etc/dracut.conf
    /etc/dracut.conf.d
    /usr/bin/dracut
    /usr/bin/lsinitrd
    /usr/lib/dracut
    /usr/lib/systemd/system/dracut-*.service
    /usr/lib/systemd/system/initrd.target.wants/dracut-*.service
    /usr/lib/systemd/system/sysinit.target.wants/dracut-*.service
Packages=
    bash
    btrfsprogs
    cryptsetup
    coreutils
    device-mapper
    erofs-utils
    jq
    plymouth
    plymouth-branding-openSUSE
    plymouth-theme-bgrt
    policycoreutils
    selinux-policy-targeted
    systemd-experimental
    util-linux
