[Content]
ExtraTrees=%D/mkosi.initrd.extra
SELinuxRelabel=no
Packages=
    bash
    btrfsprogs
    cryptsetup
    coreutils
    device-mapper
    erofs-utils
    plymouth
    plymouth-branding-openSUSE
    plymouth-theme-bgrt
    policycoreutils
    selinux-policy-targeted
    systemd-experimental
    util-linux
