# needssslcertforbuild

[Config]
MinimumVersion=27
Dependencies=
    base
    KDE
    GNOME

[Distribution]
Distribution=opensuse
Release=tumbleweed

[Output]
Format=none
OutputDirectory=mkosi.output

[Build]
Incremental=yes
CacheDirectory=mkosi.cache
PackageCacheDirectory=mkosi.pkgcache
MakeScriptsExecutable=yes


[Content]
SourceDateEpoch=1788134400
Bootable=no
