[Distribution]
Distribution=opensuse
Release=tumbleweed

[Output]
OutputDirectory=mkosi.output
ImageVersion=20260830
SplitArtifacts=yes

[Content]
Bootable=yes
UsrOnly=yes

Packages=
    openSUSE-release
    patterns-base-base
    patterns-base-hardware
    patterns-images-hardware
    kernel-default
    kernel-firmware-network

    # Core systemd
    systemd
    systemd-experimental

    # Networking
    NetworkManager
    iproute2
    iputils

    # Boot
    systemd-boot
    dosfstools

    # Essentials
    audit
    acl
    vim-small
    tar
    polkit-default-privs
    combustion
    openssh-server
    btrfsprogs
    snapper
