[Partition]
Type=root
Format=btrfs
Minimize=guess
CopyFiles=/@deployments:/@deployments
CopyFiles=/bin:/@root/bin
CopyFiles=/lib:/@root/lib
CopyFiles=/lib64:/@root/lib64
CopyFiles=/sbin:/@root/sbin
CopyFiles=/opt:/@root/opt
CopyFiles=/root:/@root/root
CopyFiles=/srv:/@root/srv
# This is the mutable live-media state. The installer uses the separate
# definitions embedded in /usr and copies /usr/share/factory/etc instead.
CopyFiles=/etc:/@etc-proto-kde-20260831
CopyFiles=/home:/@root/home
CopyFiles=/var:/@root/var
MakeDirectories=/@root/dev /@root/efi /@root/etc /@root/home /@root/media /@root/mnt /@root/proc /@root/run /@root/.system /@root/sys /@root/tmp /@root/usr /@root/var /@etc-proto-kde-20260831 /@deployments
Subvolumes=/@root /@etc-proto-kde-20260831 /@deployments
DefaultSubvolume=/@root
