[Partition]
Type=root
Label=USER
Format=btrfs
SizeMinBytes=8G
CopyFiles=/bin:/@root/bin
CopyFiles=/lib:/@root/lib
CopyFiles=/lib64:/@root/lib64
CopyFiles=/sbin:/@root/sbin
CopyFiles=/opt:/@root/opt
CopyFiles=/root:/@root/root
CopyFiles=/srv:/@root/srv
CopyFiles=/etc:/@etc
CopyFiles=/home:/@root/home
CopyFiles=/var:/@root/var
MakeDirectories=/@root/dev /@root/efi /@root/etc /@root/home /@root/media /@root/mnt /@root/opt /@root/proc /@root/root /@root/run /@root/srv /@root/.system /@root/sys /@root/tmp /@root/usr /@root/var /@etc
Subvolumes=/@root /@etc
DefaultSubvolume=/@root
GrowFileSystem=yes
SplitName=-
