d /home/installer 0755 installer users -
d /home/installer/.config 0755 installer users -
d /home/installer/Desktop 0755 installer users -
L+ /home/installer/Desktop/Install\x20proto.desktop - - - - /usr/share/applications/org.opensuse.ProtoInstaller.desktop
