[Config]
Dependencies=base

[Output]
Format=disk
Output=sys-gnome
ImageVersion=20260831
SplitArtifacts=yes

[Content]
BaseTrees=%O/base
UsrOnly=yes
Packages=
    patterns-gnome-gnome_basic
    patterns-gnome-gnome
    gdm
    firefox
    nautilus
    gnome-terminal
    gedit
