[Config]
Dependencies=base

[Output]
Format=disk
ImageId=proto-gnome
ImageVersion=20260831
Output=%i-%v.%a
CompressOutput=xz
ManifestFormat=json
SplitArtifacts=uki

[Validation]
Checksum=yes

[Content]
BaseTrees=%O/base
ExtraTrees=%D/mkosi.extra
SELinuxRelabel=no
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
FinalizeScripts=%D/mkosi.finalize.chroot
PostOutputScripts=%D/mkosi.postoutput
KernelCommandLine=
    root=gpt-auto
    rootfstype=btrfs
    rw
    security=selinux
    selinux=1
    enforcing=0
    system.deployment=proto-gnome-20260831.x86-64
    rd.systemd.mount-extra=/dev/gpt-auto-root:/sysroot/.system:btrfs:subvol=/,nodev,nosuid,x-gvfs-hide,x-gdu.hide
    rd.systemd.mount-extra=/sysroot/.system/@deployments/proto-gnome-20260831.x86-64.usr.erofs:/sysroot/usr:erofs:ro,loop,x-systemd.requires-mounts-for=/sysroot/.system/@deployments/proto-gnome-20260831.x86-64.usr.erofs
    rd.systemd.mount-extra=/dev/gpt-auto-root:/sysroot/etc:btrfs:subvol=/@etc-proto-gnome-20260831
Packages=
    patterns-gnome-gnome_basic
    brltty-driver-speech-dispatcher
    chrome-gnome-shell
    desktop-file-utils
    gdm
    gcr-ssh-agent
    gcr-ssh-askpass
    gcr3-ssh-askpass
    gnome-backgrounds
    gnome-bluetooth
    gnome-color-manager
    gnome-control-center-color
    gnome-control-center-goa
    gnome-control-center-user-faces
    gnome-control-center-users
    gnome-disk-utility
    gnome-initial-setup
    gnome-keyring-pam
    gnome-online-accounts
    gnome-remote-desktop
    gnome-session-default-session
    gnome-session-wayland
    gnome-shell-calendar
    gnome-shell-search-provider-nautilus
    gnome-software
    gnome-system-monitor
    gnome-user-docs
    gnome-console
    gnome-text-editor
    gsf-office-thumbnailer
    gstreamer-plugins-bad
    gstreamer-plugins-good
    gvfs-backend-afc
    gvfs-backend-goa
    gvfs-backend-samba
    gvfs-backends
    gvfs-fuse
    jxl-thumbnailer
    malcontent-control
    nautilus
    nautilus-extension-seahorse
    nautilus-share
    NetworkManager-openconnect-gnome
    NetworkManager-openvpn-gnome
    openssh-askpass-gnome
    orca
    pinentry-gnome3
    polkit-gnome
    python3-nautilus
    rsvg-thumbnailer
    samba
    seahorse-daemon
    speech-dispatcher-module-espeak
    xdg-desktop-portal-gnome
    xdg-user-dirs-gtk
    yelp
    zenity
